// <auto-generated />
using System;
using MalzemeTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MalzemeTakip.Migrations
{
    [DbContext(typeof(MalzemeTakipDbContext))]
    partial class MalzemeTakipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MalzemeTakip.Models.Domain.Malzeme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MalzemeMiktar")
                        .HasColumnType("int");

                    b.Property<string>("MalzemeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Malzemeler");
                });

            modelBuilder.Entity("MalzemeTakip.Models.Domain.Yemek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MalzemeMiktar")
                        .HasColumnType("int");

                    b.Property<string>("YemekName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Yemekler");
                });

            modelBuilder.Entity("MalzemeYemek", b =>
                {
                    b.Property<Guid>("MalzemelerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("YemeklerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MalzemelerId", "YemeklerId");

                    b.HasIndex("YemeklerId");

                    b.ToTable("MalzemeYemek");
                });

            modelBuilder.Entity("MalzemeYemek", b =>
                {
                    b.HasOne("MalzemeTakip.Models.Domain.Malzeme", null)
                        .WithMany()
                        .HasForeignKey("MalzemelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MalzemeTakip.Models.Domain.Yemek", null)
                        .WithMany()
                        .HasForeignKey("YemeklerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
